baseURL = "https://kchenturtles.github.io"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
theme = "hermit-v2"

[languages]
  [languages.en]
    title = 'Kendree Chen'
    [languages.en.params]
      homeSubtitle = "I'm a student, software developer, and nonprofit president from Boston, MA"
    weight = 1
  [languages.fr]
    title = 'Kendree Chen'
    [languages.fr.params]
      homeSubtitle = "I'm a student, software developer, and nonprofit president from Boston, MA"
    weight = 2
  [languages.it]
    title = 'Kendree Chen'
    [languages.it.params]
      homeSubtitle = "I'm a student, software developer, and nonprofit president from Boston, MA"
    weight = 3
 
languageCode = "en-us"

title = "Kendree Chen"
enableGitInfo = true

pygmentsCodefences  = true
pygmentsUseClasses  = true
#hasCJKLanguage = true

rssLimit = 10

copyright = "Kendree Chen. All rights reserved."
enableEmoji = true

#[services]
#  [services.disqus]
#    shortname = ''
#  [services.googleAnalytics]
#    id = ''

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = ["lastmod", ":git", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]


[blackfriday]
  # hrefTargetBlank = true
  # noreferrerLinks = true
  # nofollowLinks = true

[taxonomies]
  tag = "tags"
  # Categories are disabled by default.
  # category = "categories"

# Enable to get proper Mathjax support
#[markup]
#  [markup.goldmark]
#    [markup.goldmark.extensions]
#      [markup.goldmark.extensions.passthrough]
#        enable = true
#        [markup.goldmark.extensions.passthrough.delimiters]
#          block = [['\[', '\]'], ['$$', '$$']]
#          inline = [['\(', '\)']]


[params]
  dateform        = "January 2006"
  dateformShort   = "January 2006"
  dateformNum     = "2006-01-02"
  dateformNumTime = "January 2006"

  description = "My personal website"
  # images = [""]
  themeColor = "#494f5c"

  homeSubtitle = "A Portfolio"
  footerCopyright = "Kendree Chen. All rights reserved"
  footerHideThemeName = true
  # bgImg = ""
  # gitUrl = "https://github.com/1bl4z3r/hermit-V2/tree/staging"

  justifyContent = false

  relatedPosts = true
  code_copy_button = false

  homeSubtitlePrinter = true
  scrollToTop = true 
  global_mathjax = false
  readTime = false
  # legacyLayout = false
  shareSocial = true
  # googleTagManager = "GTM-XXXXXXXX"
  # tagSymbol = "#"
  # categorySymbol = "‚ä≤"
  # pinned = "Pinned Posts"
  # pinnedSVGname = "pin"
  # descriptionInPosts= true
  # initialPublish = "Initally Posted on: "
  # human = ["single","posts"]
  # noIndex = false
  # denyRobots = "noindex, nofollow, noarchive"
  # allowRobots = "index, follow"
  # siteNoIndex = false
  # noIndexPages = ["404 Page not found"]
  # usesAnimation = true
  
  [[params.socialLinks]]
    name = "email"
    url = "kendree.chen@gmail.com"

  [[params.socialLinks]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/kendree-chen/"

  [[params.socialLinks]]
    name = "github"
    url = "https://github.com/kchenturtles"

[menu]

  [[menu.main]]
    name = "My Projects"
    url = "posts/"
    weight = 10

  [[menu.main]]
    name = "About Me"
    url = "about/"
    weight = 20